name: Trigger auto deployment for skipasses

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/skipasses-AutoDeployTrigger-1308e843-5eab-4613-aefb-0e3597c7618a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SKIPASSES_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SKIPASSES_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SKIPASSES_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.SKIPASSES_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SKIPASSES_REGISTRY_PASSWORD }}
          containerAppName: skipasses
          resourceGroup: my-container-apps
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


